#!/usr/bin/env python
#coding=utf-8

liste=[["Un voyage de mille kilomètres commence toujours par un premier pas","Lao Tseu"],
           ["Une biographie, ça s'invente !","Louis-Ferdinand Céline"],
           ["Sans la liberté de blâmer, il n'est point d'éloge flatteur","Beaumarchais"],
           ["La mort ne nous concerne pas. Car tant que nous existons, la mort n’est pas là. Et quand vient la mort, nous n’existons plus","Epicure"],
           ["Les hommes ne désirent pas être riches, mais être plus riches que les autres","Stuart Mill"],
           ["L’auteur, dans son œuvre, doit être comme dieu dans l’univers : présent partout et visible nulle part","Gustave Flaubert"],
           ["Je me révolte, donc je suis","Albert Camus"],
           ["Si dieu n’existait pas, il faudrait l’inventer","Voltaire"],
           ["Vous êtes un sot, en trois lettres, mon fils","Molière"],
           ["Un sot savant est plus sot qu’un sot ignorant","Molière"],
           ["Il y a des moments où tout réussit. Il ne faut pas s’effrayer. Ça passe","Jules Renard"],
           ["Chaque fois que la science avance d’un pas, c’est qu’un imbécile la pousse, sans faire exprès","Zola"],
           ["Le cœur a ses raisons que la  raison ne connaît point","Blaise Pascal"],
           ["La nature a des perfections pour montrer qu’elle est l’image de dieu, et des défauts pour montrer qu’elle n’en est que l’image","Blaise Pascal"],
           ["L’homme n’est qu’un roseau, le plus faible de la nature ; mais c’est un roseau pensant","Blaise Pascal"],
           ["L’homme jouit d’une liberté totale, mais enfermé dans un labyrinthe","Inconnu"],
           ["Qui ne connaît pas la peur ne connaît pas le courage","Inconnu"],
           ["L’éternité, c’est bien long, surtout vers la fin.","Jean d'Ormesson"],
           ["L'absence de preuve n'est pas la preuve de l'absence","Michel Jouvet"],
           ["Je pense donc je suis","René Descartes"],
           ["Tomber est permis, se relever est obligatoire","poète russe"],
           ["Le noeud de la difficulté n'est pas de savoir si l'on existe, mais ce que l'on est","Pierre Gassendi"],
           ["Celui qui est impatient d'avoir un enfant épouse une femme enceinte","proverbe africain"],
           ["Si tu te cognes la tête contre un pot et que ça sonne creux, c'est pas forcément le pot qui est vide","Proverbe africain"],
           ["Tout plaisir devient languissant quand on en joit hors de toute compagnie","David Hume"],
           ["Un monde sans désirs est un monde sans Histoire","Inconnu"],
           ["Je s'appelle Groot","Groot"]
           ]
